# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2e9c36f6ee845b08a8e7bdf0422852b3a392b813fa320413d310986cfff26c547e04b6775614b39fd2d68220f1598cd7d44b4a7f3776dd44c0584dc561dd7ef1

test:
  secret_key_base: eefb75ac4ee63446cc65740af641d4716ccf1ea58288535b6f01460d91e502e8671b9fa6d364514ad5b22aabe3e51a9ee58004b9c0011ec03e9f0293f7d971d3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
